config/routes.rb
Rails.application.routes.draw do


  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'

  root                 'home#index'
  get     'splash'  => 'home#splash'
  # get			'home'  	=> 'static_pages#home'
  get     'game'    => 'game#show'
  get 		'signup'  => 'users#new'
  get 		'login'		=> 'sessions#new'
  post 		'login'		=> 'sessions#create'
  delete  'logout'  => 'sessions#destroy'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :game

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	if !logged_in?
			redirect_to splash_url
		end
  end

  def splash
  	render layout: false
  	
  end
end

app/helpers/home_helper.rb
module HomeHelper



end

app/views/home/index.html.erb
<% provide(:title, 'home') %>
<!DOCTYPE html>
<html>
  <head>
  
  </head>
  <body>
    <div class="center jumbotron">
      <h1>Welcome to the Sample App</h1>

      <h2>
        This is the home page for the
        <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
        sample application.
      </h2>

      <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
    </div>

  <%= link_to image_tag("rails.png", alt: "Rails logo"),
            'http://rubyonrails.org/' %>
  </body>
</html>

app/views/home/splash.html.erb
<% provide(:title, 'splash') %>


<!DOCTYPE html>

<html class="splash">

  <head>
  <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
  
  </head>
  <body>
    <div class="wrapper">
      <h1>Welcome to RWBY Gems</h1>

      <h2>
        This is the website for RWBY enthusists!
      </h2>
      <nav>
	      <%= link_to "Sign in", login_path, class: "btn btn-lg btn-primary" %>
	      <%= link_to "Register", signup_path, class: "btn btn-lg btn-primary" %>
      </nav>
    </div>
  </body>
</html>